# Generated by Django 3.1.2 on 2020-11-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id_accidente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_accidente', models.DateField()),
            ],
            options={
                'db_table': 'accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesAsesoria',
            fields=[
                ('id_antecedente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion_documento', models.CharField(max_length=50)),
                ('documento', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=25)),
                ('propuesta', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_capacitacion', models.DateField()),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_rut', models.CharField(max_length=1)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('celular', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformeVisita',
            fields=[
                ('id_informe', models.BigIntegerField(primary_key=True, serialize=False)),
                ('introduccion', models.CharField(max_length=250)),
                ('resultados_evaluacion', models.CharField(max_length=500)),
                ('autoevaluacion', models.CharField(max_length=1)),
                ('doc_actualizados', models.CharField(max_length=1)),
                ('reg_interno', models.CharField(max_length=1)),
                ('doc_seremi_trabajo', models.CharField(max_length=1)),
                ('copia_documentos', models.CharField(max_length=1)),
                ('informa_riesgos', models.CharField(max_length=1)),
                ('informa_medidas', models.CharField(max_length=1)),
                ('programa_orden', models.CharField(max_length=1)),
                ('extintores', models.CharField(blank=True, max_length=1, null=True)),
                ('capacitacion_extintor', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_inventario', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_certificados', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'informe_visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialCapacitaciones',
            fields=[
                ('id_material', models.BigIntegerField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'material_capacitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialSolicitado',
            fields=[
                ('id_registro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'material_solicitado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monto_multa', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_multa', models.DateField()),
            ],
            options={
                'db_table': 'multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAccidentados',
            fields=[
                ('id_accidentados', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'registro_accidentados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monto_pago', models.BigIntegerField()),
                ('fecha_pago', models.DateField()),
            ],
            options={
                'db_table': 'registro_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id_tipo_accidente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('tipo_contrato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('costo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_rut', models.CharField(max_length=1)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('celular', models.BigIntegerField()),
                ('habilitado', models.CharField(max_length=1)),
                ('sueldo', models.BigIntegerField()),
                ('contrasena', models.CharField(max_length=100)),
                ('superuser', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitaTerreno',
            fields=[
                ('id_visita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
            ],
            options={
                'db_table': 'visita_terreno',
                'managed': False,
            },
        ),
    ]
