# Generated by Django 3.1.2 on 2020-12-03 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturaleza', models.CharField(max_length=50)),
                ('partes_accidentadas', models.CharField(max_length=50)),
                ('fuente_accidente', models.CharField(max_length=50)),
                ('fecha_accidente', models.DateField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentecliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accidente',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('fecha_capacitacion', models.DateField()),
                ('hora_capacitacion', models.CharField(max_length=50)),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciontrabajador', to=settings.AUTH_USER_MODEL)),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitacioncliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('costo', models.BigIntegerField()),
                ('fecha_contratacion', models.DateField()),
                ('rut_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='MaterialCapacitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'material_capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='VisitaTerreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('motivo_visita', models.CharField(max_length=50)),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to=settings.AUTH_USER_MODEL)),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visita_terreno',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.BigIntegerField()),
                ('fecha_pago', models.DateField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contrato')),
            ],
            options={
                'db_table': 'registro_pagos',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_multa', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_multa', models.DateField()),
                ('multa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='MaterialSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.materialcapacitaciones')),
                ('material_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.capacitacion')),
            ],
            options={
                'db_table': 'material_solicitado',
            },
        ),
        migrations.CreateModel(
            name='InformeVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.CharField(max_length=250)),
                ('resultados_evaluacion', models.CharField(max_length=500)),
                ('autoevaluacion', models.CharField(max_length=1)),
                ('doc_actualizados', models.CharField(max_length=1)),
                ('reg_interno', models.CharField(max_length=1)),
                ('doc_seremi_trabajo', models.CharField(max_length=1)),
                ('copia_documentos', models.CharField(max_length=1)),
                ('informa_riesgos', models.CharField(max_length=1)),
                ('informa_medidas', models.CharField(max_length=1)),
                ('programa_orden', models.CharField(max_length=1)),
                ('extintores', models.CharField(blank=True, max_length=1, null=True)),
                ('capacitacion_extintor', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_inventario', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_certificados', models.CharField(blank=True, max_length=1, null=True)),
                ('id_visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.visitaterreno')),
            ],
            options={
                'db_table': 'informe_visita',
            },
        ),
        migrations.CreateModel(
            name='fiscalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_revisados', models.CharField(max_length=50)),
                ('descripcion_documento', models.CharField(max_length=50)),
                ('documento', models.TextField(blank=True, null=True)),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscalizacioncliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fiscalizacion',
            },
        ),
        migrations.CreateModel(
            name='Costo_adicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_adicional', models.BigIntegerField()),
                ('fecha_costoadicional', models.DateField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contrato')),
            ],
            options={
                'db_table': 'Costo_adicional',
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=25)),
                ('propuesta', models.CharField(max_length=500)),
                ('asesoria_especial', models.CharField(max_length=2)),
                ('id_accidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accidente')),
                ('id_fiscalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fiscalizacion')),
            ],
            options={
                'db_table': 'asesoria',
            },
        ),
    ]
