# Generated by Django 3.1.2 on 2020-11-06 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accidente', models.DateField()),
            ],
            options={
                'db_table': 'accidente',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('fecha_capacitacion', models.DateField()),
            ],
            options={
                'db_table': 'capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField()),
                ('rut_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='MaterialCapacitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'material_capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_accidente',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('costo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaTerreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to='account.userprofile')),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='account.userprofile')),
            ],
            options={
                'db_table': 'visita_terreno',
            },
        ),
        migrations.CreateModel(
            name='RegistroPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.BigIntegerField()),
                ('fecha_pago', models.DateField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contrato')),
            ],
            options={
                'db_table': 'registro_pagos',
            },
        ),
        migrations.CreateModel(
            name='RegistroAccidentados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.CharField(max_length=30)),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accidente')),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentecliente', to='account.userprofile')),
            ],
            options={
                'db_table': 'registro_accidentados',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_multa', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_multa', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='MaterialSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.materialcapacitaciones')),
                ('material_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialsolicitadocapacitacion', to='account.capacitacion')),
            ],
            options={
                'db_table': 'material_solicitado',
            },
        ),
        migrations.CreateModel(
            name='InformeVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.CharField(max_length=250)),
                ('resultados_evaluacion', models.CharField(max_length=500)),
                ('autoevaluacion', models.CharField(max_length=1)),
                ('doc_actualizados', models.CharField(max_length=1)),
                ('reg_interno', models.CharField(max_length=1)),
                ('doc_seremi_trabajo', models.CharField(max_length=1)),
                ('copia_documentos', models.CharField(max_length=1)),
                ('informa_riesgos', models.CharField(max_length=1)),
                ('informa_medidas', models.CharField(max_length=1)),
                ('programa_orden', models.CharField(max_length=1)),
                ('extintores', models.CharField(blank=True, max_length=1, null=True)),
                ('capacitacion_extintor', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_inventario', models.CharField(blank=True, max_length=1, null=True)),
                ('epp_certificados', models.CharField(blank=True, max_length=1, null=True)),
                ('id_visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.visitaterreno')),
            ],
            options={
                'db_table': 'informe_visita',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.tipocontrato'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='rut_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciontrabajador', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='rut_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitacioncliente', to='account.userprofile'),
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=25)),
                ('propuesta', models.CharField(max_length=500)),
                ('visita_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.visitaterreno')),
            ],
            options={
                'db_table': 'asesoria',
            },
        ),
        migrations.CreateModel(
            name='AntecedentesAsesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_documento', models.CharField(max_length=50)),
                ('documento', models.TextField(blank=True, null=True)),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.asesoria')),
            ],
            options={
                'db_table': 'antecedentes_asesoria',
            },
        ),
        migrations.AddField(
            model_name='accidente',
            name='id_tipo_accidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tipoaccidente'),
        ),
    ]
